### ISSUE TITLE
502 Bad Gateway nginx/1.4.6 (Ubuntu) displayed when ....

### ISSUE THREAD

**Issue by hemdroids** [dcposch/scramble#109]
502 Bad Gateway
nginx/1.4.6 (Ubuntu) 

Is displayed when trying to log onto the website from both Firefox and INternet explorer, and using windows 7, not ubuntu. Havent tried on my ubuntu yet. 

Hope to all that is good that your not offline. I might have to hang myself. I have soooo much conected to scramble accounts id be up chits creek for many  login verifications and SOOOOO much private info I cant replace becaause well i never thought I'd lose scramble. 

Oi. 

hope I am jsut retarded and its a simple human error. 

Thank you

let me know at hemdroids.x86 at g m a i l and ill delt this comment

**Comment by dcposch** [comment]
@hemdroids 

I'm really sorry Scramble is down right now. It should be back up within an hour.

It's down because a server ran out of disk space. I should have set up an alert. I am resizing the server to a larger instance.

**Comment by dcposch** [comment]
Beyond that, I plan to shut down Scramble soon.

I'll make sure to provide a way to a) extract all your data and b) (if possible), set up email forwarding. I can't promise (b) yet--it depends on how difficult that turns out to be. I'll do an announcement soon.

Scramble was a fun project; I learned a lot, about crypto, about email, and about running a service. I still care a lot about making email encryption easy to use, but a webmail service implementing PGP turns out to be the wrong way to do it.

It makes me really happy to hear that there are people who still use it and care this much about it.

**Comment by dcposch** [comment]
Fixed

**Comment by hemdroids** [comment]
Extracting data really isn't the issue. Ultimately now that I know, it's my reaponsibility to make the necessary email changes at each site. 

See, say for example I set up an account at sony, Microsoft, I've used your email for every site indevidually therefore making it impossible to forget what email yadda. So I own icloud, dell, ms, pretty much very site I've communication with is sitename@scramble 

I was hoping one day it'd catch on. Idea come from being an early gmail user when users actually were more selective of whom they invited.  Had I done them what I did with your service I could have retired. 

That's ok 

Hey man thank you for your service.  

Will you be working on another mail project?

Thanks again

Josh
